# Base configs
baseurl: "https://photography.kfmei.page"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Kangfu MEI"
subtitle: "With Sony Alpha a7 II"
author: "Kangfu MEI"
header:
 title: "Photography"
 subtitle: "by Kangfu MEI"
footer:
 name: "Hey there, my name is Kangfu MEI"
 bio: "A PhD student majors in computer vision and computational photography"
 github: "Find more information about Kangfu MEI at <a href=\"https://kfmei.page\">his homepage</a> ;)"
web_design: "AJ"
social_urls: 
  github: "https://github.com/MKFMIKU"
